version: '3.1'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./nginxrp/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certs:/etc/nginx/ssl
    depends_on:
      - goapi

  goapi:
    build:
      context: .
    ports:
      - "8080:443"
    volumes:
      - ./certs/potato.cld.pem:/app/certificate.pem
      - ./certs/potato.cld-key.pem:/app/privatekey.pem
    environment:
      VIRTUAL_HOST: api.potato.cld

  goapi2:
    build:
      context: .
    ports:
      - "8081:443"
    volumes:
      - ./certs/potato.cld.pem:/app/certificate.pem
      - ./certs/potato.cld-key.pem:/app/privatekey.pem
    environment:
      VIRTUAL_HOST: api2.potato.cld

networks:
  default:
    name: local-network
